source 'http://rubygems.org'
gem 'i18n', '1.8.2'
gem 'activesupport', '6.0.3.1'
gem 'ffi', '1.12.2'
gem 'connection_pool', '2.2.2'
gem 'rake'
gem 'dgaff'
gem 'rest-client'
gem 'matrix'
gem 'tf-idf-similarity'
gem 'ruby-progressbar'
gem 'nokogiri'
gem 'hashie'
gem 'pry'
gem 'sidekiq'
gem 'cld'
gem 'fuzzy-string-match'
gem 'sinatra'
gem 'elasticsearch'
gem 'elasticsearch-dsl'
gem 'elasticsearch-persistence'
gem 'rspec'
gem 'webmock'
gem 'public_suffix', '4.0.5'
gem 'diff-lcs', '1.3'
gem 'elasticsearch-api', '7.7.0'
gem 'parallel', '1.19.1'
gem 'rack', '2.2.2'
gem 'redis', '4.1.4'